name: Unity Android Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      # checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Activate Unity License
        run: |
          echo "$UNITY_LICENSE" > Unity_v6000.ulf
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

      # commits changes
      - name: Commit Uncommitted Changes (if any)
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions Bot"
          git add .
          git commit -m "CI: Commit build artifacts" || echo "No changes to commit"
          git push

      # Installs unity
      - name: Set up Unity
        uses: game-ci/unity-builder@v3
        with:
          unityVersion: 6000.0.36f1
          targetPlatform: Android

       # builds apk
      - name: Build project
        uses: game-ci/unity-builder@v2
        with:
          targetPlatform: Android
          
       # uploads apk
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: MovieApp
          path: build/android/*.apk

  release:
    name: Release APK
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download APK
        uses: actions/checkout@v4
        with:
          name: MovieApp
          path: release

      - name: Create A github Release
        uses: softprops/action-gh-release@v2
        with:
          files: release/*.apk
          release_name: "Release v1.0${{ github.run.number}}"
          body: "Automated apk release"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
