name: Unity Android Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      # checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

       # commits changes
      - name: Commit Uncommitted Changes (if any)
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions Bot"
          git add .
          git commit -m "CI: Commit build artifacts" || echo "No changes to commit"
          git push
          
      # cache for faster builds
      - name: Cache Unity Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-Android-${{ github.run_id }} 
          restore-keys: |
            Library-Android-
            
       # Build
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: Android
          
       # uploads apk
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: MovieApp
          path: build/android/*.apk

  release:
    name: Release APK
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download APK
        uses: actions/download-artifact@v3
        with:
          name: MovieApp
          path: release

      # Ensures Tag
      - name: Ensure Git Tag Exists
        run: |
          TAG="v1.0.${{ github.run_number }}"
          
          # Ensure Git is configured
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      
          # Fetch tags to avoid "tag already exists" errors
          git fetch --tags
      
          # Create tag if it doesn’t exist
          if [ -z "$(git tag -l "$TAG")" ]; then
            git tag "$TAG"
            git push origin "$TAG"
            echo "Created and pushed new tag: $TAG"
          else
            echo "Tag already exists: $TAG"
          fi

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0.${{ github.run_number }}  # Use the newly created tag
          name: "Release v1.0.${{ github.run_number }}"
          draft: false
          prerelease: false
          files: Build/Android/Movie.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
