name: Unity Android Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Unity
        uses: game-ci/unity-builder@v3
        with:
          unityVersion: 6000.0.36f1
          targetPlatform: Android

      - name: Build project
        uses: game-ci/unity-builder@v3
        with:
          targetPlatform: Android

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: MovieApp
          path: build/android/*.apk

  release:
    name: Release APK
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download APK
        uses: actions/checkout@v4
        with:
          name: MovieApp
          path: release

      - name: Create A github Release
        uses: softprops/action-gh-release@v2
        with:
          files: release/*.apk
          release_name: "Release v1.0${{ github.run.number}"
          body: "Automated apk release"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
